{{
  config(
    materialized = 'incremental',
    unique_keys='HOST_ID'
    )
}}

SELECT 
HOST_ID,
REPLACE(HOST_NAME,' ','_') AS HOST_NAME,
HOST_SINCE AS HOST_SINCE,
IS_SUPERHOST AS IS_SUPERHOST,
RESPONSE_RATE AS RESPONSE_RATE,
CASE
WHEN RESPONSE_RATE>95  THEN 'VERY GOOD'
WHEN RESPONSE_RATE>80 THEN 'GOOD'
WHEN RESPONSE_RATE>60  THEN 'FAIR'
ELSE 'POOR'
END  as RESPONSE_RATE_QUALITY,
CREATED_AT
FROM
{{ ref('bronze_hosts') }}