aws_dbt_sf_proj:
  outputs:
    dev:
      account: DTZACNA-VA48823
      database: AIRBNB
      password: Bhagwan@100304
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ASTITVASINGH
      warehouse: COMPUTE_WH
  target: dev

